export const API_URL = "https://api.wp-sofa.chat"

export const productsData = [
    {
        rank: 1,
        store: "Pawsionate",
        title: "Baby Lovely Dogs - Personalized Custom 3D Inflated Effect Phone Case",
        img: "https://png.pngtree.com/png-vector/20240728/ourlarge/pngtree-printed-colorful-hard-back-case-cover-for-apple-iphone-11-pro-png-image_13267487.png",
        details: "3D Inflated Effect, Alex/Tin/DS, art, art3dcartoondog, artt12025, Asnoba/Ngan/PS, Best-Phonecase, BMSM-Option1, customall, dog, DS-50, Katie/Vi/PR, new, personalized, pet, Phone Case, recuzm0HsNSRsx, Thanharist",
        netRevenue: "$38,347",
        percent: "9.96%",
        quantity: 1668,
        facebook: "85.13%",
        google: "3.06%",
        tiktok: "0.84%",
        klaviyo: "3.66%",
        others: "7.31%"
    },
    {
        rank: 2,
        store: "Wrappiness",
        title: "Dog Mom Lovely Chibi - Personalized Custom 3D Inflated Effect Tumbler",
        img: "https://png.pngtree.com/png-clipart/20221022/original/pngtree-smiling-mug-png-image_8711543.png",
        details: "3D Inflated Effect, An/Nhi/PS, art, art3dcartoondog, artAI, artichipbak, artt12025, Asnoba/Ngan/PS, bestsellingTumbler, customall, dog, dog mom, dog mum, DS-0, gg-mothersday, Jane/Nha/DS, Katie/Vi/PR, personalized, pet, recuzh0XuLJQp, scale, Thanharist, Tumbler, Uyentrist",
        netRevenue: "$47,704",
        percent: "8.64%",
        quantity: 1446,
        facebook: "77.25%",
        google: "7.61%",
        tiktok: "4.56%",
        klaviyo: "2.9%",
        others: "7.68%"
    },
    {
        rank: 3,
        store: "Wrappiness",
        title: "I Punch A Bitch For You My Friend - Personalized Custom Pink Marble Mug",
        img: "https://media.istockphoto.com/id/171368204/vi/anh/red-cup.jpg?s=612x612&w=0&k=20&c=l8FsK4DLE_L-gg2CQvhBoZOAz9PNUxa4TKtS5u6lT4s=",
        details: "art, artbraz, Asnoba/Ngan/PS, customall, for bestie, for friend, Him/Nhi/DS, Katie/Vi/PR, mug, new, personalized, Pink Marble Mug, recuxi7hjPfpT",
        netRevenue: "$29,689",
        percent: "6.57%",
        quantity: 1100,
        facebook: "89.91%",
        google: "4.82%",
        tiktok: "0%",
        klaviyo: "1.36%",
        others: "3.91%"
    },
    {
        rank: 4,
        store: "Wrappiness",
        title: "You're Going to be a Job - Personalized Custom Baby Onesie",
        img: "https://city89.com/wp-content/uploads/2023/04/sp-0051-mockup-black-front.jpg",
        details: "apparel, artholiday, Baby-one-sie, Emma/Suong/PS, first-mothersday, for family, for mom, gg-mothersday, Katelyn/Ha/DS, Mia/Mai/PR, mothers day, new arrivals, personalized, single product",
        netRevenue: "$28,289",
        percent: "6.33%",
        quantity: 1060,
        facebook: "90.38%",
        google: "0.94%",
        tiktok: "0%",
        klaviyo: "1.79%",
        others: "6.89%"
    },
    {
        rank: 5,
        store: "Wrappiness",
        title: "I Wish We Lived Closer Floral Version - Personalized Custom 3D Inflated Effect Mug",
        img: "https://aothun24h.vn/userfile/products/12242/2023_11_03_15_19_50_87.jpg",
        details: "3D Inflated Effect, art, best-selling mug, Coffee Mug, customall, edge to edge coffee mug, for bestie, for friend, Jena/Nhi/PS, mug, Neil/Nam/DS, personalized, Quin/Quynh/PR, recutMEiZlf0fc, scale",
        netRevenue: "$14,940",
        percent: "3.65%",
        quantity: 612,
        facebook: "81.21%",
        google: "5.88%",
        tiktok: "0%",
        klaviyo: "6.7%",
        others: "6.21%"
    },
    {
        rank: 6,
        store: "Wrappiness",
        title: "Whiskey Glass Gift Box - Well box it for you (maximum 1 item per box)",
        img: "https://i.pinimg.com/736x/f0/d2/8b/f0d28bd47314ae30cff8c019e89d3c48.jpg",
        details: "exclude-recommendation, gift-box, non-custom, recomatic-no, SEARCHANISE_IGNORE",
        netRevenue: "$2,480",
        percent: "2.97%",
        quantity: 497,
        facebook: "78.07%",
        google: "9.26%",
        tiktok: "0.8%",
        klaviyo: "6.64%",
        others: "5.23%"
    },
    {
        rank: 7,
        store: "Wrappiness",
        title: "Package Protection (Recommended for Fragile Items)",
        img: "https://quatanghandmade.net/media/uploads/2014/12/in-anh-len-coc-trang-long-mau-quai-tron.jpg",
        details: "exclude-recommendation, gift-box, non-custom, recomatic-no, SEARCHANISE_IGNORE",
        netRevenue: "$1,456",
        percent: "2.91%",
        quantity: 487,
        facebook: "82.55%",
        google: "8.42%",
        tiktok: "0%",
        klaviyo: "3.9%",
        others: "5.13%"
    },
    {
        rank: 8,
        store: "Wrappiness",
        title: "Besties Sitting Together - Personalized Custom Car Visor Clip",
        img: "https://bizweb.dktcdn.net/thumb/grande/100/175/849/products/ava-2e71d6e6-294f-481c-b2a1-1200f7d792a4.jpg?v=1596094024303",
        details: "Alice/Anh/PR, art, artbackview, BMSM-Option1, BMSM-Option123, Car Visor Clip, customall, for bestie, for friend, Lona/Loan/PS, Na/Nguyen/DS, new, personalized, recuk9e9xA9Dzt",
        netRevenue: "$8,276",
        percent: "2.47%",
        quantity: 414,
        facebook: "97.1%",
        google: "1.45%",
        tiktok: "0%",
        klaviyo: "1.21%",
        others: "0.24%"
    },
    {
        rank: 9,
        store: "Pawsionate",
        title: "Priority Production",
        img: "https://gomdep.vn/wp-content/uploads/2022/11/coc-su-in-logo-theo-yeu-cau.jpg",
        details: "mystery product, new arrivals, non-custom, recomatic-no, SEARCHANISE_IGNORE",
        netRevenue: "$923.91",
        percent: "1.85%",
        quantity: 309,
        facebook: "66.34%",
        google: "13.92%",
        tiktok: "2.59%",
        klaviyo: "7.44%",
        others: "9.71%"
    },
    {
        rank: 10,
        store: "Wrappiness",
        title: "Never Too Far To Drink Together - Personalized Custom Whiskey Glass",
        img: "https://www.inlogo.vn/vnt_upload/product/12_2016/in_ly_su_14_2.jpg",
        details: "art, customall, for bestie, for friend, Gin/Quynh/DS, Lona/Loan/PS, personalized, Quin/Quynh/PR, recuz41lc1AZ3D, Trend, Whiskey Glass",
        netRevenue: "$7,314",
        percent: "1.62%",
        quantity: 271,
        facebook: "84.5%",
        google: "4.8%",
        tiktok: "0%",
        klaviyo: "2.58%",
        others: "8.12%"
    },
    {
        rank: 11,
        store: "Pawsionate",
        title: "Package Protection (Recommended for Fragile Items)",
        img: "https://product.hstatic.net/200000438087/product/a40_5dbcff80b05b4b85a6b81aad15373dc1_1e139176186348ed9ffefbe085c3c857_master.jpg",
        details: "mystery product, new arrivals, non-custom, recomatic-no, SEARCHANISE_IGNORE",
        netRevenue: "$774.41",
        percent: "1.55%",
        quantity: 259,
        facebook: "65.64%",
        google: "13.13%",
        tiktok: "1.54%",
        klaviyo: "7.72%",
        others: "11.97%"
    },
    {
        rank: 12,
        store: "Wrappiness",
        title: "Sisters Are Different Flowers From The Same Garden - Personalized Custom 3D Inflated Effect Coffee Mug",
        img: "https://miahome.vn/wp-content/uploads/2024/04/photogift-love-4-oo.jpg",
        details: "3D Inflated Effect, Alice/Anh/PR, BOGO-mail, Coffee Mug, customall, edge to edge coffee mug, for bestie, for brother, for family, for friend, for sibling, Hana/Nga/PS, Katelyn/Ha/DS, mug, personalized, recuqmoRUtCk3, scale",
        netRevenue: "$6,199",
        percent: "1.52%",
        quantity: 254,
        facebook: "90.16%",
        google: "5.51%",
        tiktok: "0%",
        klaviyo: "1.18%",
        others: "3.15%"
    },
    {
        rank: 13,
        store: "Pawsionate",
        title: "Baby Lovely Pet - Personalized Custom 3D Inflated Effect Phone Case",
        img: "https://sagoga.com/wp-content/uploads/2021/09/in-op-lung-dien-thoai-theo-yeu-cau-chat-luong-cao-1.jpg",
        details: "3D Inflated Effect, Alex/Tin/DS, art, art3dcartoondog, art3dcartoondog, artt12025, BMSM-Option1, customall, dog, DS-0, Hana/Nga/PS, Katie/Vi/PR, personalized, pet, Phone Case, recuBVhApVlAWq, scale, Thanharist",
        netRevenue: "$5,816",
        percent: "1.51%",
        quantity: 253,
        facebook: "83.4%",
        google: "3.95%",
        tiktok: "0.4%",
        klaviyo: "2.37%",
        others: "9.88%"
    },
    {
        rank: 14,
        store: "Wrappiness",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://product.hstatic.net/200000424005/product/z3457454639275_5fac02c105e3a71736c5295bd9dad848_16b8dde46bb5417c9b7547eecf70d82c_master.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 15,
        store: "Wrappiness",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://colorbook.vn/image/catalog/Blog/Tin-tuc-2022/0-Tin-tuc-2023/T09/in-anh-theo-yeu-cau/loi-ich-khi-in-anh-theo-yeu-cau.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 16,
        store: "Wrappiness",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://miahome.vn/wp-content/uploads/2024/04/photogift-love-khugn-tu-nhien-1.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 17,
        store: "Wrappiness",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://tuongvip.vn/public/uploads/products/62049/qua-tang-ki-niem-y-nghia-in-hinh-theo-yeu-cau-a5-a4-khung-anh-mau-tu-chon.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 18,
        store: "Wrappiness",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://shopquatang.org/wp-content/uploads/2016/09/ly-su-trang-thuong.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 19,
        store: "Pawsionate",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://vuabinhnuoc.vn/wp-content/uploads/2021/03/coc-su-in-logo-theo-yeu-cau.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 20,
        store: "Wrappiness",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://hopgiayrvc.com/wp-content/uploads/I76I.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 21,
        store: "Pawsionate",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://dongphuchaianh.vn/wp-content/uploads/2022/04/in-ao-phong-theo-yeu-cau-ben.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 22,
        store: "Pawsionate",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://gomdep.vn/wp-content/uploads/2022/11/coc-su-in-logo-theo-yeu-cau.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 23,
        store: "Wrappiness",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://inchi.vn/data/thumbnails/qua-tang/qua-tang-gia-dinh-ban-be/coc-in-ten-va-ngay-thang-0.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 24,
        store: "Pawsionate",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfFxva9cCVjO8MwsLetnmlvwVPPpOWyZdgmA&s",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
    {
        rank: 25,
        store: "Pawsionate",
        title: "Custom Photo Your Wings Were Ready - Personalized Custom Solar Light",
        img: "https://shopquatang.org/wp-content/uploads/2016/09/ly-su-trang-thuong.jpg",
        details: "best-solar light, for memorial, Lee/Duy/DS, Loren/Nhi/PR, memorial, new arrivals, personalized, photo upload, scale, solar light, Tracey/Thao/PS",
        netRevenue: "$8,328",
        percent: "1.42%",
        quantity: 238,
        facebook: "89.92%",
        google: "2.94%",
        tiktok: "0%",
        klaviyo: "2.94%",
        others: "4.2%"
    },
];
